version: '3'

services:
  service_registry:
    build:
      context: .
      dockerfile: DockerfileServiceRegistry
    hostname: my-registry

  peer:
    build:
      context: .
      dockerfile: DockerfilePeer
    depends_on:
      - service_registry
    links:
      - service_registry
    deploy:
      replicas: 5

